version: "3"
services:
  app:
    environment:
      FREEDESKTOP_MIME_TYPES_PATH: /usr/local/share/mime/packages/freedesktop.org.xml
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb 
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /var/tmp
      - sockets:/app/tmp/sockets
    tty: true
    depends_on:
      - db
    extends:
      file: ./docker/postgres/password.yml
      service: password
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - '5433:5432'
    volumes:
      - psgl_data:/var/lib/postgresql/data
    extends:  
      file: ./docker/postgres/password.yml
      service: password
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
      #socketファイルの共有
    volumes: 
      - sockets:/app/tmp/sockets
    depends_on: 
      - app

volumes:
  psgl_data:
  sockets: